version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./www/:/var/www/
      - ./server/nginx1/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"

  php:
    build: .
    container_name: php-container
    volumes:
      - ./www/:/var/www/
    ports:
      - "9001:9000"

  nginx2:
    image: nginx:latest
    container_name: nginx2-container
    volumes:
      - ./www/:/var/www/
      - ./server/nginx2/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
  
  php2:
    build: .
    container_name: php2-container
    volumes:
      - ./www/:/var/www/
    ports:
      - "9002:9000"


# A suivre MySql et PhpMyAdmin